### ISSUE TITLE
导入后总是提示user.setUsername setPassword， account.setUser  setPassword  这一类找不到方法

### ISSUE THREAD

**Issue by AlexYY0** [jerryshell/passwordbox-angular-springboot-back-end#1]
RT
导入后总是提示user.setUsername setPassword， account.setUser  setPassword  这一类找不到方法。不知道是不是自己导入的方式错误

**Comment by jerryshell** [comment]
我在项目中使用了 lombok ，这个插件可以自动实现 Getter/Setter 等方法，你给你的 ide 装上这个插件之后应该就没有错误提示了。

**Comment by AlexYY0** [comment]
好的  我试试   请问你修改过后的版本是前后端分离的吗? 就是前端和后端可以放到不同的服务器上吗？抱歉，这方面不太熟悉，一直很困惑！

**Comment by jerryshell** [comment]
这是前后端分离的，相应的前端在[这里](https://github.com/jerryshell/passwordbox-angular-springboot-front-end)，没有前后端分离前的原项目在[这里](https://github.com/jerryshell/passwordbox)

**Comment by AlexYY0** [comment]
好的   因为我正在上大学，所以对前后端不分离还比较了解，对前后端分离不怎么了解，不知道他们是怎么运作通信的，我再看看！
